Backend theme for social registry.
OpenG2P/openg2p-social-registry pull request #29
Opened 2024-07-31 11:55 UTC by klbtheprogrammer

Added backend theme for social registry.
This module is dependent on the muk_backend_theme.

2024-08-14 07:20 UTC, shibu-narayanan approved these changes

2024-08-14 07:51 UTC, klbtheprogrammer commented
Precommit issue was because the README.rst was missing. I've added it.

2024-08-21 18:23 UTC, mkumar-02 approved these changes

2024-08-30 12:08 UTC, mkumar-02 requested changes
Not working as expected. Can you install the standalone module and see the changes.

![Screenshot from 2024-08-30 17-34-55](https://github.com/user-attachments/assets/dda847eb-ffea-4049-a0cf-f16d250b4485)

2024-12-18 08:10 UTC, closed without merging